// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeCharm.Model.AuditFramework.T4Templates
{
    using System.Data;
    using CodeCharm.Entity.AuditFramework;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class CreateTrigger : CreateTriggerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 5 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
SchemaDataSet schemaDataSet = _params.SchemaDataSet;
SchemaDataSet.SchemaPrimaryKeysDataTable primaryKeysTable = schemaDataSet.SchemaPrimaryKeys;
EnumerableRowCollection<SchemaDataSet.SchemaPrimaryKeysRow> primaryKeysRows = primaryKeysTable.AsEnumerable();
var primaryKeysQuery = from primaryKeysRow in primaryKeysRows
                       where primaryKeysRow.TABLE_SCHEMA.Equals(_schema, StringComparison.OrdinalIgnoreCase)
                       where primaryKeysRow.TABLE_NAME.Equals(_tableName, StringComparison.OrdinalIgnoreCase)
                       select primaryKeysRow;
bool first = true;

            
            #line default
            #line hidden
            this.Write("IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N\'[");
            
            #line 15 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 15 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 15 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("]\'))\r\n    DROP TRIGGER [");
            
            #line 16 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 16 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 16 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("];\r\nIF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N\'[");
            
            #line 17 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 17 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 17 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºInsert]\'))\r\n    DROP TRIGGER [");
            
            #line 18 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 18 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 18 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºInsert];\r\nIF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N\'[" +
                    "");
            
            #line 19 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 19 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 19 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºUpdate]\'))\r\n    DROP TRIGGER [");
            
            #line 20 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 20 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 20 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºUpdate];\r\nIF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N\'[" +
                    "");
            
            #line 21 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 21 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 21 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºDelete]\'))\r\n    DROP TRIGGER [");
            
            #line 22 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 22 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 22 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("ºDelete];\r\nGO\r\n\r\nCREATE TRIGGER [");
            
            #line 25 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 25 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 25 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("]\r\n   ON  [");
            
            #line 26 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 26 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write(@"] 
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
/*
    READ THIS BEFORE EDITING THIS CODE
    ----------------------------------
    This code was automatically generated by the
    CodeCharm.Model.AuditFramework
    project.
    
    If you modify this code, and then execute 
    the AuditFramework tool, your modifications
    will be ignored and overwritten.
    
    Template: CreateTrigger.tt
*/
    SET NOCOUNT ON;

	BEGIN TRY
	    DECLARE @TrackºId                           [BIGINT];
	    DECLARE @AuditºTimeStampUtc                 [DATETIME];
	    DECLARE @AuditºTransactionSequence          [BIGINT];
	    DECLARE @AuditºTransactionDepth             [INT];
	    DECLARE @AuditºAction                       [NCHAR](1);
	    DECLARE @AuditºDesignatedUserId             [SYSNAME];
	    DECLARE @AuditºTransactionLastUpdatedUtc    [DATETIME];
	    DECLARE @AuditºIsLocalTransactionSequence   [BIT];
	    DECLARE @AuditºTransactionSequenceInt       [BIGINT];
	    
	    EXECUTE [");
            
            #line 56 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write(@"].CurrentTransactionSequence 
	          @AuditºTransactionSequence OUTPUT
	        , @AuditºTransactionDepth OUTPUT
	        , @AuditºDesignatedUserId OUTPUT
	        , @AuditºTransactionLastUpdatedUtc OUTPUT;

	    SET @AuditºTransactionSequenceInt = ISNULL(@AuditºTransactionSequence, 0);
	    SET @AuditºIsLocalTransactionSequence = ~ CONVERT(BIT, @AuditºTransactionSequenceInt);
		
	    IF @AuditºIsLocalTransactionSequence <> 0
	    BEGIN
	        EXECUTE [");
            
            #line 67 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[RequestTransactionSequence] \r\n\t              NULL\r\n\t            , @AuditºTrans" +
                    "actionSequence OUTPUT\r\n\t            , @AuditºTransactionDepth OUTPUT;\r\n\t    END;" +
                    "\r\n\r\n\t");
            
            #line 73 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	string insertedTableName = _schema + "º" + _tableName + "ºInserted";
	string deletedTableName = _schema + "º" + _tableName + "ºDeleted";
	
            
            #line default
            #line hidden
            this.Write("\t    SELECT\r\n\t");
            
            #line 78 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t            ");
            
            #line 82 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", ");
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 82 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 83 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t        INTO #");
            
            #line 86 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(insertedTableName));
            
            #line default
            #line hidden
            this.Write(" \r\n\t        FROM [inserted];\r\n\t    \r\n\t    SELECT\r\n\t");
            
            #line 90 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t            ");
            
            #line 94 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", ");
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 94 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 95 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t        INTO #");
            
            #line 98 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deletedTableName));
            
            #line default
            #line hidden
            this.Write(" \r\n\t        FROM [deleted];\r\n\t    \r\n\t    DECLARE @InsertºCount   INT;\r\n\t    DECLA" +
                    "RE @DeleteºCount   INT;\r\n\t    \r\n\t    SELECT @InsertºCount = COUNT(*) FROM #");
            
            #line 104 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(insertedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t    SELECT @DeleteºCount = COUNT(*) FROM #");
            
            #line 105 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deletedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t    SET @AuditºAction = \'U\';\r\n\t    IF @DeleteºCount = 0\r\n\t        SET @Audi" +
                    "tºAction = \'I\';\r\n\t    IF @InsertºCount = 0\r\n\t        SET @AuditºAction = \'D\';\r\n\r" +
                    "\n\t-- Variables to hold values of primary keys\r\n\t");
            
            #line 114 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t    DECLARE @");
            
            #line 117 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaHelper.DataTypeWithDetail(primaryKeysRow, schemaDataSet.Columns)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 118 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	}   
            
            #line default
            #line hidden
            this.Write("\r\n\t    IF @InsertºCount > 0\r\n\t    BEGIN\r\n\t        -- Could be Insert or Update\r\n\t" +
                    "        IF @InsertºCount = 1\r\n\t        BEGIN\r\n\t            SELECT \r\n\t");
            
            #line 127 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                    ");
            
            #line 131 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", ");
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 131 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write(" = [");
            
            #line 131 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 132 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t                FROM #");
            
            #line 135 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(insertedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t            EXECUTE [");
            
            #line 137 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[Trackº");
            
            #line 137 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 137 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("] \r\n\t                @AuditºTransactionSequence\r\n\t              , @AuditºTransact" +
                    "ionDepth\r\n\t              , @AuditºAction\r\n\t              , @TrackºId OUTPUT\r\n\t  " +
                    "            , @AuditºTimeStampUtc OUTPUT\r\n\t              , @AuditºDesignatedUser" +
                    "Id\r\n\t");
            
            #line 144 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t              , @");
            
            #line 147 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 148 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	}   
            
            #line default
            #line hidden
            this.Write("\t\t\t  ;\r\n\r\n\t        END  \r\n\t        ELSE\r\n\t        BEGIN\r\n\t            DECLARE ins" +
                    "ert_cursor CURSOR LOCAL\r\n\t                FAST_FORWARD\r\n\t                FOR SEL" +
                    "ECT\r\n\t");
            
            #line 157 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                        ");
            
            #line 161 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 161 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 162 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"

	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t                    FROM #");
            
            #line 165 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(insertedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t            OPEN insert_cursor;\r\n\t            \r\n\t                FETCH NEXT" +
                    " FROM insert_cursor INTO \r\n\t                    ");
            
            #line 170 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
	    Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 174 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(primaryKeysRow.COLUMN_NAME);
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t                WHILE @@FETCH_STATUS = 0\r\n\t                    BEGIN\r\n\t    " +
                    "                    EXECUTE [");
            
            #line 180 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[Trackº");
            
            #line 180 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 180 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write(@"] 
	                              @AuditºTransactionSequence
	                            , @AuditºTransactionDepth
	                            , @AuditºAction
	                            , @TrackºId OUTPUT
	                            , @AuditºTimeStampUtc OUTPUT
	                            , @AuditºDesignatedUserId
	");
            
            #line 187 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                            , @");
            
            #line 190 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 191 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"

	}   
            
            #line default
            #line hidden
            this.Write("                            ;\r\n\r\n\t                        FETCH NEXT FROM insert_" +
                    "cursor INTO \r\n\t                            ");
            
            #line 195 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
	    Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 199 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(primaryKeysRow.COLUMN_NAME);
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t                    END;\r\n\r\n\t            CLOSE insert_cursor;\r\n\t        END" +
                    "\r\n\t    END\r\n\t    ELSE\r\n\t    BEGIN\r\n\t        -- Can only be Delete\r\n\t        IF @" +
                    "DeleteºCount = 1\r\n\t        BEGIN\r\n\t            SELECT \r\n\t");
            
            #line 214 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                    ");
            
            #line 218 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", ");
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 218 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write(" = [");
            
            #line 218 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 219 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t                FROM #");
            
            #line 222 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deletedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t            EXECUTE [");
            
            #line 224 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[Trackº");
            
            #line 224 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 224 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write("] \r\n\t                @AuditºTransactionSequence\r\n\t              , @AuditºTransact" +
                    "ionDepth\r\n\t              , @AuditºAction\r\n\t              , @TrackºId OUTPUT\r\n\t  " +
                    "            , @AuditºTimeStampUtc OUTPUT\r\n\t              , @AuditºDesignatedUser" +
                    "Id\r\n\t");
            
            #line 231 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t              , @");
            
            #line 234 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 235 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	}   
            
            #line default
            #line hidden
            this.Write("              ;\r\n\r\n\t        END  \r\n\t        ELSE\r\n\t        BEGIN\r\n\t            DE" +
                    "CLARE delete_cursor CURSOR LOCAL\r\n\t                FAST_FORWARD\r\n\t              " +
                    "  FOR SELECT\r\n\t");
            
            #line 244 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                        ");
            
            #line 248 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 248 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("]\r\n\t");
            
            #line 249 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"

	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write("\t                    FROM #");
            
            #line 252 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deletedTableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t            OPEN delete_cursor;\r\n\t                FETCH NEXT FROM delete_cu" +
                    "rsor INTO \r\n\t                    ");
            
            #line 256 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
	    Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 260 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(primaryKeysRow.COLUMN_NAME);
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t                WHILE @@FETCH_STATUS = 0\r\n\t                    BEGIN\r\n\t    " +
                    "                    EXECUTE [");
            
            #line 266 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[Trackº");
            
            #line 266 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_schema));
            
            #line default
            #line hidden
            this.Write("º");
            
            #line 266 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_tableName));
            
            #line default
            #line hidden
            this.Write(@"] 
	                            @AuditºTransactionSequence
	                          , @AuditºTransactionDepth
	                          , @AuditºAction
	                          , @TrackºId OUTPUT
	                          , @AuditºTimeStampUtc OUTPUT
	                          , @AuditºDesignatedUserId
	");
            
            #line 273 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
            
            #line default
            #line hidden
            this.Write("\t                          , @");
            
            #line 276 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeysRow.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 277 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"

	}   
            
            #line default
            #line hidden
            this.Write("                          ;\r\n\r\n\t                        FETCH NEXT FROM delete_cu" +
                    "rsor INTO \r\n\t                            ");
            
            #line 281 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 
	first = true;
	foreach (SchemaDataSet.SchemaPrimaryKeysRow primaryKeysRow in primaryKeysQuery)
	{   
	    Write(first ? "  " : ", "); 
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 285 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
 Write(primaryKeysRow.COLUMN_NAME);
	    first = false;
	}   
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t                    END;\r\n\r\n\t            CLOSE delete_cursor;\r\n\t        END" +
                    ";\r\n\t    END;\r\n\r\n\t    IF @AuditºIsLocalTransactionSequence <> 0\r\n\t    BEGIN\r\n\t   " +
                    "     EXECUTE [");
            
            #line 297 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateTrigger.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[ReleaseTransactionSequence] \r\n\t              @AuditºTransactionSequence\r\n\t    " +
                    "        , @AuditºTransactionDepth;\r\n\t    END;\r\n\tEND TRY\r\n\tBEGIN CATCH\r\n\t    DECL" +
                    "ARE\t  @ErrorMessage    NVARCHAR(4000)\r\n\t\t\t  \t, @ErrorNumber     INT\r\n\t\t\t\t, @Erro" +
                    "rSeverity   INT\r\n\t\t\t\t, @ErrorState      INT\r\n\t\t\t\t, @ErrorLine       INT\r\n\t\t\t\t, @" +
                    "ErrorProcedure  NVARCHAR(200);\r\n\r\n\t    -- Assign variables to error-handling fun" +
                    "ctions that \r\n\t    -- capture information for RAISERROR.\r\n\t    SELECT\t  @ErrorNu" +
                    "mber = ERROR_NUMBER()\r\n\t\t\t\t, @ErrorSeverity = ERROR_SEVERITY()\r\n\t\t\t\t, @ErrorStat" +
                    "e = ERROR_STATE()\r\n\t\t\t\t, @ErrorLine = ERROR_LINE()\r\n\t\t\t\t, @ErrorProcedure = ISNU" +
                    "LL(ERROR_PROCEDURE(), \'-\');\r\n\r\n\t    -- Build the message string that will contai" +
                    "n original\r\n\t    -- error information.\r\n\t    SELECT @ErrorMessage = N\'Error %d, " +
                    "Level %d, State %d, Procedure %s, Line %d, Message: \'+ ERROR_MESSAGE();\r\n\t\t\r\n\t\tI" +
                    "F @ErrorState = 0\r\n\t\t\tSET @ErrorState = 1;\r\n\r\n\t    -- Raise an error: msg_str pa" +
                    "rameter of RAISERROR will contain\r\n\t    -- the original error information.\r\n\t   " +
                    " RAISERROR \r\n\t        (\r\n\t          @ErrorMessage \r\n\t        , @ErrorSeverity \r\n" +
                    "\t        , 1               \r\n\t        , @ErrorNumber    \t-- parameter: original " +
                    "error number.\r\n\t        , @ErrorSeverity  \t-- parameter: original error severity" +
                    ".\r\n\t        , @ErrorState     \t-- parameter: original error state.\r\n\t        , @" +
                    "ErrorProcedure \t-- parameter: original error procedure name.\r\n\t        , @ErrorL" +
                    "ine       \t-- parameter: original error line number.\r\n\t        );\r\n\r\n\tEND CATCH;" +
                    "\r\n\r\nEND\r\nGO\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class CreateTriggerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
