// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeCharm.Model.AuditFramework.T4Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class CreateRequestTransactionSequenceProcedure : CreateRequestTransactionSequenceProcedureBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N\'[");
            
            #line 2 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[RequestTransactionSequence]\') AND type IN (N\'P\', N\'PC\'))\r\n    DROP PROCEDURE [" +
                    "");
            
            #line 3 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[RequestTransactionSequence]\r\nGO\r\n\r\nCREATE PROCEDURE [");
            
            #line 6 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write(@"].[RequestTransactionSequence] 
  @UserName             SYSNAME
, @TransactionSequence  BIGINT  OUTPUT
, @Depth                INT     OUTPUT
AS
BEGIN
/*
    READ THIS BEFORE EDITING THIS CODE
    ----------------------------------
    This code was automatically generated by the
    CodeCharm.Model.AuditFramework
    project.
    
    If you modify this code, and then execute 
    the AuditFramework tool, your modifications
    will be ignored and overwritten.
    
    Template: CreateRequestTransactionSequenceProcedure.tt
*/

    SET NOCOUNT ON;

    DECLARE @StartNewTransaction BIT

	BEGIN TRY
	    BEGIN TRANSACTION;
	    SAVE TRANSACTION RequestTransactionSequence;

	    SET @StartNewTransaction = 0;

	    IF EXISTS(  SELECT      *
	                    FROM    [");
            
            #line 37 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[SessionTransaction]\r\n\t                    WHERE   [SessionId] = @@SPID\r\n\t     " +
                    "                   AND [Host_Name] = HOST_NAME()\r\n\t                        AND [" +
                    "App_Name] = APP_NAME()\r\n\t                )\r\n\t    BEGIN\r\n\t        UPDATE  [");
            
            #line 43 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[SessionTransaction]\r\n\t            SET [Depth] = [Depth] + 1\r\n\t            WHER" +
                    "E   [SessionId] = @@SPID;\r\n\r\n\t        SELECT    @TransactionSequence = [ActiveSe" +
                    "quence]\r\n\t                , @Depth = [Depth]\r\n\t            FROM    [");
            
            #line 49 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[SessionTransaction]\r\n\t            WHERE   SessionId = @@SPID;\r\n\t    END;\r\n\t   " +
                    " ELSE\r\n\t    BEGIN\r\n\t        SET @StartNewTransaction = 1;\r\n\t    END;\r\n\r\n\t    IF " +
                    "1 = @StartNewTransaction\r\n\t    BEGIN\r\n\t        INSERT INTO [");
            
            #line 59 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[TransactionSequence]\r\n\t            DEFAULT VALUES;\r\n\r\n\t        SET @Transactio" +
                    "nSequence = SCOPE_IDENTITY();\r\n\r\n\t        DELETE FROM [");
            
            #line 64 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[TransactionSequence]\r\n\t            WHERE   [TransactionSequence] = @Transactio" +
                    "nSequence;\r\n\r\n\t        DELETE FROM [");
            
            #line 67 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[SessionTransaction]\r\n\t            WHERE   [SessionId] = @@SPID;\r\n\r\n\t        SE" +
                    "T @Depth = 1;\r\n\r\n\t        INSERT INTO [");
            
            #line 72 "C:\Users\mcbeea\Desktop\AuditFramework\Model.AuditFramework\T4Templates\CreateRequestTransactionSequenceProcedure.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_params.AuditingSchema));
            
            #line default
            #line hidden
            this.Write("].[SessionTransaction]\r\n\t            (\r\n\t              [SessionId]\r\n\t            " +
                    ", [ActiveSequence]\r\n\t            , [Depth]\r\n\t            , [User_Name]\r\n\t       " +
                    "     , [Host_Name]\r\n\t            , [App_Name]\r\n\t            , [LastUpdatedUtc]\r\n" +
                    "\t            )\r\n\t            VALUES\r\n\t            (\r\n\t              @@SPID\r\n\t   " +
                    "         , @TransactionSequence\r\n\t            , @Depth\r\n\t            , @UserName" +
                    "\r\n\t            , HOST_NAME()\r\n\t            , APP_NAME()\r\n\t            , GETUTCDA" +
                    "TE()\r\n\t            );\r\n\r\n\t    END;\r\n\r\n\t    COMMIT TRANSACTION;\r\n\tEND TRY\r\n\tBEGIN" +
                    " CATCH\r\n\t    DECLARE\t  @ErrorMessage    NVARCHAR(4000)\r\n\t\t\t  \t, @ErrorNumber    " +
                    " INT\r\n\t\t\t\t, @ErrorSeverity   INT\r\n\t\t\t\t, @ErrorState      INT\r\n\t\t\t\t, @ErrorLine  " +
                    "     INT\r\n\t\t\t\t, @ErrorProcedure  NVARCHAR(200);\r\n\r\n\t    -- Assign variables to e" +
                    "rror-handling functions that \r\n\t    -- capture information for RAISERROR.\r\n\t    " +
                    "SELECT\t  @ErrorNumber = ERROR_NUMBER()\r\n\t\t\t\t, @ErrorSeverity = ERROR_SEVERITY()\r" +
                    "\n\t\t\t\t, @ErrorState = ERROR_STATE()\r\n\t\t\t\t, @ErrorLine = ERROR_LINE()\r\n\t\t\t\t, @Erro" +
                    "rProcedure = ISNULL(ERROR_PROCEDURE(), \'-\');\r\n\r\n\t\tIF XACT_STATE() = -1 -- uncomm" +
                    "ittable\r\n\t\tBEGIN\r\n\t\t\tROLLBACK TRANSACTION RequestTransactionSequence;\r\n\t\tEND;\r\n\t" +
                    "\t\r\n\t\tIF XACT_STATE() = 1 -- committable\r\n\t\tBEGIN\r\n\t\t\tCOMMIT TRANSACTION;\r\n\t\tEND;" +
                    "\r\n\t\t\r\n\t    -- Build the message string that will contain original\r\n\t    -- error" +
                    " information.\r\n\t    SELECT @ErrorMessage = N\'Error %d, Level %d, State %d, Proce" +
                    "dure %s, Line %d, Message: \'+ ERROR_MESSAGE();\r\n\t\t\r\n\t\tIF @ErrorState = 0\r\n\t\t\tSET" +
                    " @ErrorState = 1;\r\n\r\n\t    -- Raise an error: msg_str parameter of RAISERROR will" +
                    " contain\r\n\t    -- the original error information.\r\n\t    RAISERROR \r\n\t        (\r\n" +
                    "\t          @ErrorMessage \r\n\t        , @ErrorSeverity \r\n\t        , 1             " +
                    "  \r\n\t        , @ErrorNumber    \t-- parameter: original error number.\r\n\t        ," +
                    " @ErrorSeverity  \t-- parameter: original error severity.\r\n\t        , @ErrorState" +
                    "     \t-- parameter: original error state.\r\n\t        , @ErrorProcedure \t-- parame" +
                    "ter: original error procedure name.\r\n\t        , @ErrorLine       \t-- parameter: " +
                    "original error line number.\r\n\t        );\r\n\tEND CATCH;\r\nEND\r\nGO\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class CreateRequestTransactionSequenceProcedureBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
